//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("Technique", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class TechniqueType {
    
    private DocumentationType documentationField;
    
    private ExtensionScopeType extensionScopeField;
    
    private SampleRoleBlueprintType[] sampleRoleBlueprintField;
    
    private ExperimentDataRoleBlueprintType[] experimentDataRoleBlueprintField;
    
    private CategoryBlueprintType[] methodBlueprintField;
    
    private ResultBlueprintType[] resultBlueprintField;
    
    private LiteratureReferenceType[] bibliographyField;
    
    private string versionField;
    
    private string nameField;
    
    private bool extensionField;
    
    private bool abstractField;
    
    public TechniqueType() {
        this.versionField = "0.90";
        this.extensionField = false;
        this.abstractField = false;
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    public ExtensionScopeType ExtensionScope {
        get {
            return this.extensionScopeField;
        }
        set {
            this.extensionScopeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SampleRoleBlueprint")]
    public SampleRoleBlueprintType[] SampleRoleBlueprint {
        get {
            return this.sampleRoleBlueprintField;
        }
        set {
            this.sampleRoleBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExperimentDataRoleBlueprint")]
    public ExperimentDataRoleBlueprintType[] ExperimentDataRoleBlueprint {
        get {
            return this.experimentDataRoleBlueprintField;
        }
        set {
            this.experimentDataRoleBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CategoryBlueprint", IsNullable=false)]
    public CategoryBlueprintType[] MethodBlueprint {
        get {
            return this.methodBlueprintField;
        }
        set {
            this.methodBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ResultBlueprint")]
    public ResultBlueprintType[] ResultBlueprint {
        get {
            return this.resultBlueprintField;
        }
        set {
            this.resultBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("LiteratureReference", IsNullable=false)]
    public LiteratureReferenceType[] Bibliography {
        get {
            return this.bibliographyField;
        }
        set {
            this.bibliographyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool extension {
        get {
            return this.extensionField;
        }
        set {
            this.extensionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(false)]
    public bool @abstract {
        get {
            return this.abstractField;
        }
        set {
            this.abstractField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("Documentation", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class DocumentationType {
    
    private string literatureReferenceIDField;
    
    private string literatureAccessionField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string literatureReferenceID {
        get {
            return this.literatureReferenceIDField;
        }
        set {
            this.literatureReferenceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string literatureAccession {
        get {
            return this.literatureAccessionField;
        }
        set {
            this.literatureAccessionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(AllowedValueType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(NumericValueType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public partial class ParameterValueType {
    
    private DocumentationType documentationField;
    
    private object itemField;
    
    private ItemChoiceType itemElementNameField;
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Boolean", typeof(bool))]
    [System.Xml.Serialization.XmlElementAttribute("D", typeof(double))]
    [System.Xml.Serialization.XmlElementAttribute("DateTime", typeof(System.DateTime))]
    [System.Xml.Serialization.XmlElementAttribute("EmbeddedXML", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("F", typeof(float))]
    [System.Xml.Serialization.XmlElementAttribute("I", typeof(int))]
    [System.Xml.Serialization.XmlElementAttribute("L", typeof(long))]
    [System.Xml.Serialization.XmlElementAttribute("PNG", typeof(byte[]), DataType="base64Binary")]
    [System.Xml.Serialization.XmlElementAttribute("S", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("SVG", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    D,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    EmbeddedXML,
    
    /// <remarks/>
    F,
    
    /// <remarks/>
    I,
    
    /// <remarks/>
    L,
    
    /// <remarks/>
    PNG,
    
    /// <remarks/>
    S,
    
    /// <remarks/>
    SVG,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MaxType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MinType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public partial class NumericValueType : ParameterValueType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public partial class QuantityType {
    
    private UnitType[] unitField;
    
    private AllowedRangeType[] allowedRangeField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Unit")]
    public UnitType[] Unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AllowedRange")]
    public AllowedRangeType[] AllowedRange {
        get {
            return this.allowedRangeField;
        }
        set {
            this.allowedRangeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("Unit", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class UnitType {
    
    private SIUnitType[] sIUnitField;
    
    private string labelField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SIUnit")]
    public SIUnitType[] SIUnit {
        get {
            return this.sIUnitField;
        }
        set {
            this.sIUnitField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("SIUnit", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class SIUnitType {
    
    private double factorField;
    
    private double exponentField;
    
    private double offsetField;
    
    private SIUnitNameList valueField;
    
    public SIUnitType() {
        this.factorField = 1D;
        this.exponentField = 1D;
        this.offsetField = 0D;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1D)]
    public double factor {
        get {
            return this.factorField;
        }
        set {
            this.factorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(1D)]
    public double exponent {
        get {
            return this.exponentField;
        }
        set {
            this.exponentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(0D)]
    public double offset {
        get {
            return this.offsetField;
        }
        set {
            this.offsetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public SIUnitNameList Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public enum SIUnitNameList {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("1")]
    Item1,
    
    /// <remarks/>
    m,
    
    /// <remarks/>
    kg,
    
    /// <remarks/>
    s,
    
    /// <remarks/>
    A,
    
    /// <remarks/>
    K,
    
    /// <remarks/>
    mol,
    
    /// <remarks/>
    cd,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("AllowedRange", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class AllowedRangeType {
    
    private DocumentationType documentationField;
    
    private MinType minField;
    
    private MaxType maxField;
    
    private string unitField;
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    public MinType Min {
        get {
            return this.minField;
        }
        set {
            this.minField = value;
        }
    }
    
    /// <remarks/>
    public MaxType Max {
        get {
            return this.maxField;
        }
        set {
            this.maxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string unit {
        get {
            return this.unitField;
        }
        set {
            this.unitField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("Min", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class MinType : NumericValueType {
    
    private bool includedField;
    
    public MinType() {
        this.includedField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool included {
        get {
            return this.includedField;
        }
        set {
            this.includedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("Max", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class MaxType : NumericValueType {
    
    private bool includedField;
    
    public MaxType() {
        this.includedField = true;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool included {
        get {
            return this.includedField;
        }
        set {
            this.includedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("ExtensionScope", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class ExtensionScopeType {
    
    private ExtendedTechniqueType[] extendedTechniqueField;
    
    private ExtendedExtensionType[] extendedExtensionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExtendedTechnique")]
    public ExtendedTechniqueType[] ExtendedTechnique {
        get {
            return this.extendedTechniqueField;
        }
        set {
            this.extendedTechniqueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ExtendedExtension")]
    public ExtendedExtensionType[] ExtendedExtension {
        get {
            return this.extendedExtensionField;
        }
        set {
            this.extendedExtensionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("ExtendedTechnique", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class ExtendedTechniqueType {
    
    private string nameField;
    
    private string uriField;
    
    private string sha256Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string sha256 {
        get {
            return this.sha256Field;
        }
        set {
            this.sha256Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("ExtendedExtension", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class ExtendedExtensionType {
    
    private string nameField;
    
    private string uriField;
    
    private string sha256Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string sha256 {
        get {
            return this.sha256Field;
        }
        set {
            this.sha256Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("SampleRoleBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class SampleRoleBlueprintType {
    
    private DocumentationType documentationField;
    
    private CategoryBlueprintType[] categoryBlueprintField;
    
    private string nameField;
    
    private PurposeType samplePurposeField;
    
    private ModalityType modalityField;
    
    private string maxOccursField;
    
    private bool inheritableField;
    
    public SampleRoleBlueprintType() {
        this.modalityField = ModalityType.required;
        this.maxOccursField = "1";
        this.inheritableField = true;
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CategoryBlueprint")]
    public CategoryBlueprintType[] CategoryBlueprint {
        get {
            return this.categoryBlueprintField;
        }
        set {
            this.categoryBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PurposeType samplePurpose {
        get {
            return this.samplePurposeField;
        }
        set {
            this.samplePurposeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string maxOccurs {
        get {
            return this.maxOccursField;
        }
        set {
            this.maxOccursField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(true)]
    public bool inheritable {
        get {
            return this.inheritableField;
        }
        set {
            this.inheritableField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("CategoryBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class CategoryBlueprintType {
    
    private DocumentationType documentationField;
    
    private SeriesSetBlueprintType[] seriesSetBlueprintField;
    
    private ParameterBlueprintType[] parameterBlueprintField;
    
    private CategoryBlueprintType[] categoryBlueprintField;
    
    private string nameField;
    
    private ModalityType modalityField;
    
    private string maxOccursField;
    
    public CategoryBlueprintType() {
        this.modalityField = ModalityType.required;
        this.maxOccursField = "1";
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SeriesSetBlueprint")]
    public SeriesSetBlueprintType[] SeriesSetBlueprint {
        get {
            return this.seriesSetBlueprintField;
        }
        set {
            this.seriesSetBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ParameterBlueprint")]
    public ParameterBlueprintType[] ParameterBlueprint {
        get {
            return this.parameterBlueprintField;
        }
        set {
            this.parameterBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CategoryBlueprint")]
    public CategoryBlueprintType[] CategoryBlueprint {
        get {
            return this.categoryBlueprintField;
        }
        set {
            this.categoryBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string maxOccurs {
        get {
            return this.maxOccursField;
        }
        set {
            this.maxOccursField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("SeriesSetBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class SeriesSetBlueprintType {
    
    private DocumentationType documentationField;
    
    private object[] itemsField;
    
    private string nameField;
    
    private ModalityType modalityField;
    
    public SeriesSetBlueprintType() {
        this.modalityField = ModalityType.required;
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SeriesBlueprint", typeof(SeriesBlueprintType))]
    [System.Xml.Serialization.XmlElementAttribute("SeriesBlueprintChoice", typeof(SeriesBlueprintChoiceType))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("SeriesBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class SeriesBlueprintType {
    
    private DocumentationType documentationField;
    
    private Quantity[] quantityField;
    
    private AllowedValueType[] allowedValueField;
    
    private string nameField;
    
    private SeriesTypeType seriesTypeField;
    
    private ModalityType modalityField;
    
    private PlotScaleType plotScaleField;
    
    private DependencyType dependencyField;
    
    private string maxOccursField;
    
    public SeriesBlueprintType() {
        this.modalityField = ModalityType.required;
        this.plotScaleField = PlotScaleType.linear;
        this.maxOccursField = "1";
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Quantity")]
    public Quantity[] Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AllowedValue")]
    public AllowedValueType[] AllowedValue {
        get {
            return this.allowedValueField;
        }
        set {
            this.allowedValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SeriesTypeType seriesType {
        get {
            return this.seriesTypeField;
        }
        set {
            this.seriesTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(PlotScaleType.linear)]
    public PlotScaleType plotScale {
        get {
            return this.plotScaleField;
        }
        set {
            this.plotScaleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public DependencyType dependency {
        get {
            return this.dependencyField;
        }
        set {
            this.dependencyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string maxOccurs {
        get {
            return this.maxOccursField;
        }
        set {
            this.maxOccursField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class Quantity : QuantityType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("AllowedValue", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class AllowedValueType : ParameterValueType {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public enum SeriesTypeType {
    
    /// <remarks/>
    Int,
    
    /// <remarks/>
    Float,
    
    /// <remarks/>
    Numeric,
    
    /// <remarks/>
    String,
    
    /// <remarks/>
    Boolean,
    
    /// <remarks/>
    DateTime,
    
    /// <remarks/>
    EmbeddedXML,
    
    /// <remarks/>
    PNG,
    
    /// <remarks/>
    SVG,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public enum ModalityType {
    
    /// <remarks/>
    required,
    
    /// <remarks/>
    optional,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public enum PlotScaleType {
    
    /// <remarks/>
    linear,
    
    /// <remarks/>
    log,
    
    /// <remarks/>
    ln,
    
    /// <remarks/>
    none,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public enum DependencyType {
    
    /// <remarks/>
    independent,
    
    /// <remarks/>
    dependent,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("SeriesBlueprintChoice", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class SeriesBlueprintChoiceType {
    
    private DocumentationType documentationField;
    
    private SeriesBlueprintType[] seriesBlueprintField;
    
    private ModalityType modalityField;
    
    public SeriesBlueprintChoiceType() {
        this.modalityField = ModalityType.required;
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("SeriesBlueprint")]
    public SeriesBlueprintType[] SeriesBlueprint {
        get {
            return this.seriesBlueprintField;
        }
        set {
            this.seriesBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("ParameterBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class ParameterBlueprintType {
    
    private DocumentationType documentationField;
    
    private object[] itemsField;
    
    private string nameField;
    
    private SeriesTypeType parameterTypeField;
    
    private ModalityType modalityField;
    
    private string maxOccursField;
    
    public ParameterBlueprintType() {
        this.modalityField = ModalityType.required;
        this.maxOccursField = "1";
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AllowedValue", typeof(AllowedValueType))]
    [System.Xml.Serialization.XmlElementAttribute("Quantity", typeof(Quantity))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public SeriesTypeType parameterType {
        get {
            return this.parameterTypeField;
        }
        set {
            this.parameterTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string maxOccurs {
        get {
            return this.maxOccursField;
        }
        set {
            this.maxOccursField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
public enum PurposeType {
    
    /// <remarks/>
    produced,
    
    /// <remarks/>
    consumed,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("ExperimentDataRoleBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class ExperimentDataRoleBlueprintType {
    
    private DocumentationType documentationField;
    
    private string nameField;
    
    private PurposeType experimentStepPurposeField;
    
    private ModalityType modalityField;
    
    private string maxOccursField;
    
    public ExperimentDataRoleBlueprintType() {
        this.modalityField = ModalityType.required;
        this.maxOccursField = "1";
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public PurposeType experimentStepPurpose {
        get {
            return this.experimentStepPurposeField;
        }
        set {
            this.experimentStepPurposeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string maxOccurs {
        get {
            return this.maxOccursField;
        }
        set {
            this.maxOccursField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("ResultBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class ResultBlueprintType {
    
    private DocumentationType documentationField;
    
    private SeriesSetBlueprintType seriesSetBlueprintField;
    
    private CategoryBlueprintType[] categoryBlueprintField;
    
    private string nameField;
    
    private ModalityType modalityField;
    
    private string maxOccursField;
    
    public ResultBlueprintType() {
        this.modalityField = ModalityType.required;
        this.maxOccursField = "1";
    }
    
    /// <remarks/>
    public DocumentationType Documentation {
        get {
            return this.documentationField;
        }
        set {
            this.documentationField = value;
        }
    }
    
    /// <remarks/>
    public SeriesSetBlueprintType SeriesSetBlueprint {
        get {
            return this.seriesSetBlueprintField;
        }
        set {
            this.seriesSetBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CategoryBlueprint")]
    public CategoryBlueprintType[] CategoryBlueprint {
        get {
            return this.categoryBlueprintField;
        }
        set {
            this.categoryBlueprintField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(ModalityType.required)]
    public ModalityType modality {
        get {
            return this.modalityField;
        }
        set {
            this.modalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute("1")]
    public string maxOccurs {
        get {
            return this.maxOccursField;
        }
        set {
            this.maxOccursField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("LiteratureReference", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class LiteratureReferenceType {
    
    private string literatureReferenceIDField;
    
    private string uriField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="token")]
    public string literatureReferenceID {
        get {
            return this.literatureReferenceIDField;
        }
        set {
            this.literatureReferenceIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string uri {
        get {
            return this.uriField;
        }
        set {
            this.uriField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("MethodBlueprint", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class MethodBlueprintType {
    
    private CategoryBlueprintType[] categoryBlueprintField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CategoryBlueprint")]
    public CategoryBlueprintType[] CategoryBlueprint {
        get {
            return this.categoryBlueprintField;
        }
        set {
            this.categoryBlueprintField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:org:astm:animl:schema:technique:draft:0.90")]
[System.Xml.Serialization.XmlRootAttribute("Bibliography", Namespace="urn:org:astm:animl:schema:technique:draft:0.90", IsNullable=false)]
public partial class BibliographyType {
    
    private LiteratureReferenceType[] literatureReferenceField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("LiteratureReference")]
    public LiteratureReferenceType[] LiteratureReference {
        get {
            return this.literatureReferenceField;
        }
        set {
            this.literatureReferenceField = value;
        }
    }
}
